### ISSUE TITLE
No results for searches

### ISSUE THREAD

**Issue by kevinliam** [carlosp420/VoSeq#336]
Hi Carlos! Searches in the "Code or Taxon Name"  box on the VoSeq home page don't return any results. I'm running VoSeq locally on an Ubuntu 14.04 machine according to the "Easy and quick install" instructions provided [here](http://carlosp420.github.io/VoSeq/intro/install.html). I'm running Ubuntu 14.04.

Kevin

**Comment by carlosp420** [comment]
Hi Kevin,

thanks for your feedback.
I just corrected some of the Vagrant files that were causing the problem:

1. Increase RAM to 1024 MB. The search engine, elasticsearch, needs more RAM than the 512 MB that was allocated before. I tested with 512 MB and elasticsearch crashed all the time, so VoSeq worked but the search tool did not work.
2. I upgraded the Vagrant files to install elasticsearch 1.7.3
3. Fixed the Make file to install the test data using the local settings (uploading the data to the PostgreSQL installation).

After these fixes, I did some tests and it was possible to search by code. You need to update your cloned repository of Voseq with the command `git pull origin master`. Then destroy your Vagrant virtual machine and create a new one: `vagrant destroy` and then `vagrant up`.

**Comment by mariespe** [comment]
I have the most recent code, but the search is still not working. Destroying and creating a new virtual machine didn't help. Voseq is installed locally on my Macbook  Pro (OSX 10.11.5) using the quick and easy install.

**Comment by carlosp420** [comment]
Well, I just tested again the  installation of VoSeq using the "Quick install" and the search function works fine at least in my Linux Ubuntu host. Unfortunately, I don't have any Mac available for testing.

Things to note:
* Make sure that the search backend, elasticsearch, is running. Use the command to start it (if it is already running, there is no harm in running this command anyway): `sudo service elasticsearch start`
* After you add, delete or update records in voseq (vouchers, sequences, etc) you need to update the elasticsearch index using the commands:
```shell
workon voseq
cd /vagrant
make index
```
This will add or remove records from the index so the search function of VoSeq will work taking into account the recent changes to your data. You can automate this using a cronjob depending on how often you add/delete/modify your data so you don't need to update the index manually.

A successful indexing of your data should look like this, in the console:
```
Indexing 10 Vouchers
/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Sequences.time_created received a naive datetime (2016-07-18 03:43:22.804556) while time zone support is active.
  RuntimeWarning)

Indexing 6 Sequences
/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Vouchers.modified received a naive datetime (2016-07-18 03:43:23.035715) while time zone support is active.
  RuntimeWarning)

Indexing 10 Vouchers
/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Vouchers.modified received a naive datetime (2016-07-18 03:43:23.827043) while time zone support is active.
  RuntimeWarning)

Indexing 10 Vouchers
```

Once it is finished you can try and the search functions should work: http://imgur.com/4oZ0urx
